### ISSUE TITLE
Add Flag to Bypass SSH Host Thumbprint Verification

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [gregtwallace/apc-p15-tool#4]
Hello.

Thanks for the utility.
Is it possible to add an option that would allow accepting any fingerprints of keys?

**Comment by gregtwallace** [comment]
Hello,

You mean for the `install` function, correct? What is the use case? I considered adding a flag for it, but it is a security risk to blindly upload private keys to an unconfirmed host. That's the reason the log produces a message with the host key so you can confirm it is trusted and then copy it into the appropriate flag.

Cheers.

**Comment by Aleksey-Maksimov** [comment]
Maybe I'm wrong, but the talk about "unconfirmed host" may seem strange given the fact that I have an administrative account and password to connect to a remote host and install a certificate. Moreover, when we think about the need to update a certificate on tens and hundreds of hosts (I’m talking about automation), manually confirming the key of each host is a very strange method.

**Comment by gregtwallace** [comment]
The attack vector is Man in the Middle. If you do not verify the host key, an attacker could insert themselves in between you and the UPS. The attacker could pass your credentials to the UPS and return the UPS responses to you, but decrypt everything in the middle without you knowing.

Verifying the SSH thumbprint verifies you're connecting directly to the UPS, without a man in the middle, since a MITM does not possess your SSH server's key, and therefore the attacker would present a different thumbprint.

Automating this in a large environment only increases the attack surface, making the verification more important. I would script getting the thumbprints of all of the UPSes and run it on a device that has a known secure physical link to your devices, save the thumbprints, and then incorporate that in my SSL cert update script.

Obviously this is extra work but necessary work if you don't want to risk a MITM stealing both your UPS credentials and the private keys your UPSes use.

All of that said, I think it is a valid request to request an override flag, but the security risks should not be overlooked. You absolutely should NOT automate a large environment and ignore host keys. This makes it extremely easy for an attacker to steal your credentials and keys. Additionally, I am writing from a place of updating your SSL certs every 60 days since that is the Let's Encrypt lifetime. If you're using self-signed certs that last a decade, your one time upload of keys/certs is lower risk, though certainly not no-risk.

I would not accept not verifying host keys in a business or production environment.
